print("This Madlibs is inspired by Mad Lib Theater with Benedict Cumberbatch on The Tonight Show Starring Jimmy Fallon.")

male_name = input("Male name: ")
fav_teacher = input("Name of your favorite teacher(Add Ms or Mr): ")
exclamation = input("Exclamation: ")
number = input("Number: ")
plural_obj = input("Plural object: ")
store_name = input("Store name: ")
body_part = input("Body part: ")
silly_word = input("Silly word: ")
holiday_name = input("Name of a holiday: ")
movie = input("Movie title: ")
verb_ing = input("Verb ends with -ing: ")
distance = input("Amount of distance(Add m, cm, mm, etc.): ")
country = input("A country: ")
animal = input("Animal: ")
famous_quote = input("Famous movie quote: ")
body_part_2 = input("Another body part: ")
children_song = input("Children song: ")
adj = input("Adjective: ")

print(f"\n\nBenedict: Hello, I'm detective {male_name}. And you are?")
print(f"\nJimmy: {fav_teacher}.")
print("\nBenedict: You're here today under the suspicion of a Second-degree robbery.")
print(f"\nJimmy: {exclamation}!")
print(f"\nBenedict: That's right. {number} {plural_obj} was stolen from {store_name}. And the crime scene has your {body_part} written all over it.")
print(f"\nJimmy: That is {silly_word}!")
print(f"\nBenedict: Where were you on the night of {holiday_name}?")
print(f"\nJimmy: We were watching {movie}.")
print(f"\nBenedict: Then why the security camera footage show you {verb_ing} just {distance} away from the crime scene?")
print("\nBenedict: Alright. Alright. I'm full with playing games. Where are you from?") 
print(f"\nJimmy: {country}.")
print(f"\nBenedict: Yeah. Just as I suspected. Do you know one of the best part about being a detective is that I get to lock up criminals like you and go home to my children and my pet {animal}. And say {famous_quote}!")
print(f"\nJimmy: Fine, I did this. I committed the robbery. But I only did this because i needed the money to buy myself {body_part_2} implant.")
print(f"\nBenedict: I knew it all along. I knew it all along! And everytime I saw a crime, I'd like to sing my favorite song {children_song}.")
print(f"\nJimmy: You have a {adj} voice. I LOVE YOU.")
print("\n\nEND SCENE")