print("This Madlibs is inspired by Mad Lib Theater with Benedict Cumberbatch on The Tonight Show Starring Jimmy Fallon.")

male_name = input("Male name: ")
fav_teacher = input("Name of your favorite teacher: ")
exclamation = input("Exclamation: ")
number = input("Number: ")
plural_obj = input("Plural object: ")
store_name = input("Store name: ")
body_part = input("Body part: ")
silly_word = input("Silly word: ")
holiday_name = input("Name of a holiday: ")
movie = input("Movie title: ")
verb_ing = input("Verb ends with -ing: ")
distance = input("Amount of distance: ")
country = input("A country: ")
animal = input("Animal: ")
famous_quote = input("Famous movie quote: ")
body_part_2 = input("Another body part: ")